version: "3.3"
services:
  mysqlservice:
    image: mysql:latest
    ports:
      - 3306:3306
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AuthenticationDB
      MYSQL_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  webservice:
    container_name: web-container
    build: .
    ports:
      - 8088:80
    depends_on:
      - mysqlservice
    restart: always
